linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - gofmt
    - goimports

linters-settings:
  errcheck:
    check-type-assertions: true

run:
  timeout: 5m
