package agent

import (
	"context"
	"fmt"
	"strings"

	"github.com/packetcode/packetcode/internal/provider"
)

// charsPerToken is the heuristic the context manager uses to estimate
// tokens from string lengths. 4.0 is the rule-of-thumb for English text;
// CJK and code skew lower (more tokens per char) but the heuristic is
// deliberately conservative — better to over-estimate than under, since
// the only consequence is suggesting /compact slightly early.
const charsPerToken = 4.0

// ContextManager handles token estimation and conversation compaction.
// It's stateless — methods operate on the messages and config the caller
// passes in.
type ContextManager struct {
	threshold int // percent at which auto-suggest fires (e.g. 80)
}

func NewContextManager(threshold int) *ContextManager {
	if threshold <= 0 || threshold > 100 {
		threshold = 80
	}
	return &ContextManager{threshold: threshold}
}

// EstimateTokens returns an approximate token count for a slice of
// messages. Counts content + tool call arguments + tool result strings.
//
// We deliberately use a character-length heuristic rather than tiktoken
// because tiktoken-go requires CGO on some platforms and the precision
// isn't worth the dependency: the only consumer is "should we suggest
// compaction?" — being off by 20% is fine.
func (cm *ContextManager) EstimateTokens(messages []provider.Message) int {
	chars := 0
	for _, m := range messages {
		chars += len(m.Content)
		for _, tc := range m.ToolCalls {
			chars += len(tc.Name) + len(tc.Arguments)
		}
		// Add a per-message overhead for role + structural tokens.
		chars += 8
	}
	return int(float64(chars) / charsPerToken)
}

// UsagePercent returns current context usage as a percentage of the
// model's window. Returns 0 if maxTokens is 0 (unknown — e.g. Ollama).
func (cm *ContextManager) UsagePercent(messages []provider.Message, maxTokens int) int {
	if maxTokens <= 0 {
		return 0
	}
	used := cm.EstimateTokens(messages)
	pct := used * 100 / maxTokens
	if pct > 100 {
		pct = 100
	}
	return pct
}

// ShouldSuggestCompact reports whether the running conversation has
// crossed the auto-suggest threshold.
func (cm *ContextManager) ShouldSuggestCompact(messages []provider.Message, maxTokens int) bool {
	return cm.UsagePercent(messages, maxTokens) >= cm.threshold
}

// Compact summarises the middle of the conversation into a single
// assistant message, keeping the system prompt and the last keepRecent
// messages verbatim.
//
// The summary itself is generated by asking the active LLM to summarise
// the messages-to-be-collapsed in 200 words or so. That round-trip is
// expensive, so callers should only invoke this when explicitly asked
// (the /compact command) or when a hard context limit is imminent.
func (cm *ContextManager) Compact(
	ctx context.Context,
	prov provider.Provider,
	modelID string,
	messages []provider.Message,
	keepRecent int,
) ([]provider.Message, error) {
	if len(messages) <= keepRecent+1 {
		return normalizeToolTranscript(messages), nil
	}

	// Identify the system prompt (if any) and the tail to preserve.
	var systemMsgs []provider.Message
	body := messages
	if len(messages) > 0 && messages[0].Role == provider.RoleSystem {
		systemMsgs = []provider.Message{messages[0]}
		body = messages[1:]
	}
	if len(body) <= keepRecent {
		return normalizeToolTranscript(messages), nil
	}
	toSummarize := body[:len(body)-keepRecent]
	tailStart := compactTailStart(body, len(body)-keepRecent)
	toSummarize = body[:tailStart]
	tail := body[tailStart:]

	prompt := buildSummaryPrompt(toSummarize)

	req := provider.ChatRequest{
		Model:  modelID,
		Stream: true,
		Messages: []provider.Message{
			{Role: provider.RoleUser, Content: prompt},
		},
	}
	stream, err := prov.ChatCompletion(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("compact: request: %w", err)
	}
	var summary strings.Builder
	for ev := range stream {
		switch ev.Type {
		case provider.EventTextDelta:
			summary.WriteString(ev.TextDelta)
		case provider.EventError:
			return nil, fmt.Errorf("compact: stream: %w", ev.Error)
		}
	}

	summaryMsg := provider.Message{
		Role:    provider.RoleAssistant,
		Content: "[Conversation summary so far]\n" + strings.TrimSpace(summary.String()),
	}
	out := append([]provider.Message{}, systemMsgs...)
	out = append(out, summaryMsg)
	out = append(out, tail...)
	return normalizeToolTranscript(out), nil
}

func buildSummaryPrompt(messages []provider.Message) string {
	var b strings.Builder
	b.WriteString("Summarise the following conversation between a user and an AI coding agent. ")
	b.WriteString("Capture: the user's overall goal, key decisions, file paths touched, ")
	b.WriteString("commands run, and any open threads. Keep it under 250 words. ")
	b.WriteString("Output the summary as plain prose with no preamble.\n\n")
	b.WriteString("---\n\n")
	for _, m := range messages {
		b.WriteString(string(m.Role))
		b.WriteString(": ")
		b.WriteString(m.Content)
		for _, tc := range m.ToolCalls {
			fmt.Fprintf(&b, "\n  [tool call: %s(%s)]", tc.Name, tc.Arguments)
		}
		b.WriteString("\n\n")
	}
	return b.String()
}

type toolGroup struct {
	start int
	end   int
}

func compactTailStart(messages []provider.Message, start int) int {
	if start <= 0 {
		return 0
	}
	if start >= len(messages) {
		return len(messages)
	}
	for _, group := range completeToolGroups(messages) {
		if start > group.start && start < group.end {
			return group.start
		}
	}
	return start
}

func completeToolGroups(messages []provider.Message) []toolGroup {
	var groups []toolGroup
	for i := 0; i < len(messages); i++ {
		msg := messages[i]
		if msg.Role != provider.RoleAssistant || len(msg.ToolCalls) == 0 {
			continue
		}
		_, next, ok := collectToolResults(messages, i)
		if !ok {
			continue
		}
		groups = append(groups, toolGroup{start: i, end: next})
		i = next - 1
	}
	return groups
}

func normalizeToolTranscript(messages []provider.Message) []provider.Message {
	if len(messages) == 0 {
		return messages
	}
	out := make([]provider.Message, 0, len(messages))
	for i := 0; i < len(messages); i++ {
		msg := messages[i]
		switch {
		case msg.Role == provider.RoleTool:
			continue
		case msg.Role == provider.RoleAssistant && len(msg.ToolCalls) > 0:
			results, next, ok := collectToolResults(messages, i)
			if !ok {
				msg.ToolCalls = nil
				if msg.Content != "" {
					out = append(out, msg)
				}
				continue
			}
			out = append(out, msg)
			out = append(out, results...)
			i = next - 1
		default:
			out = append(out, msg)
		}
	}
	return out
}

func collectToolResults(messages []provider.Message, assistantIndex int) ([]provider.Message, int, bool) {
	if assistantIndex < 0 || assistantIndex >= len(messages) {
		return nil, assistantIndex + 1, false
	}
	calls := messages[assistantIndex].ToolCalls
	if len(calls) == 0 {
		return nil, assistantIndex + 1, true
	}

	matched := make([]bool, len(calls))
	results := make([]provider.Message, 0, len(calls))
	next := assistantIndex + 1
	for next < len(messages) && messages[next].Role == provider.RoleTool {
		result := messages[next]
		if callIdx := matchingToolCallIndex(calls, result, matched); callIdx >= 0 {
			call := calls[callIdx]
			if result.ToolCallID == "" && call.ID != "" {
				result.ToolCallID = call.ID
			}
			if result.Name == "" {
				result.Name = call.Name
			}
			matched[callIdx] = true
			results = append(results, result)
		}
		next++
	}
	if len(results) != len(calls) {
		return results, next, false
	}
	for _, ok := range matched {
		if !ok {
			return results, next, false
		}
	}
	return results, next, true
}

func matchingToolCallIndex(calls []provider.ToolCall, result provider.Message, matched []bool) int {
	for i, call := range calls {
		if matched[i] {
			continue
		}
		if call.ID != "" && result.ToolCallID == call.ID {
			return i
		}
	}
	for i, call := range calls {
		if matched[i] {
			continue
		}
		if call.Name != "" && result.Name == call.Name {
			return i
		}
	}
	return -1
}
